### ISSUE TITLE
Tried running helm install --values helm_charts/vault/values-prod.yaml --name vault-prod --namespace vault helm_charts/vault Error: failed to download "helm_charts/vault" 

### ISSUE THREAD

**Issue by anillingutla** [ReadyTalk/vault-helm-chart#32]
Issue 1 - 
helm install --values helm_charts/vault/values-prod.yaml --name vault-prod --namespace vault helm_charts/vault
Doesnt have the values-prod.yaml

Issue 2 - 
Error: failed to download "helm_charts/vault"
Where is the correct path.. first command itself is failing...

**Comment by bartlettc22** [comment]
Hi @anillingutla - I've merged in an update to our readme that may help with your issues.  The values-prod.yaml was an example of something you might create to customize your values.  If you don't have any custom values, you can leave the flag off of the helm install command.  

As for the failed to download message, unfortuneatly we don't have this in the public repository yet so you'll have to clone this repo first and use it from there (see README)

**Comment by bartlettc22** [comment]
Closing due to lack of response.
