### ISSUE TITLE
preInstallConsul job fails with Read-only file system

### ISSUE THREAD

**Issue by Chrislevi** [ReadyTalk/vault-helm-chart#42]
kubectl version: 
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:13:31Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}

when I run `helm install --name vault --namespace vault  helm_charts/vault` it prints `Error: timed out waiting for the condition` due to preInstallConsul job failure.
I extended the JobDeadline but it didn't help obviously.

seems like the preInstallConsul cant manage to run command `chmod -R +x /pre-install` 
 job's log:
`chmod: /pre-install: Read-only file system`

job's mound description:
    `Mounts:`
     ` /etc/podinfo from podinfo (ro)`
    `/pre-install from pre-install (rw)`

Any ideas?
Thanks for the help.

**Comment by Chrislevi** [comment]
@bartlettc22 Any help?

**Comment by Chrislevi** [comment]
https://github.com/kubernetes/kubernetes/pull/58720
I assume the job flow worked, this PR could be related?

**Comment by idcmp** [comment]
Same problem here. Sadly, makes this project unusable until it's resolved.

**Comment by Chrislevi** [comment]
@idcmp I've forked the project and fixed the problem, there's an open PR for the fix, its pretty simple to implement by yourself. -> #43
